# Generated by Django 2.1.2 on 2019-02-01 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='orderNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 18, 38, 19, 355304, tzinfo=utc)),
        ),
    ]
