# Generated by Django 2.1.2 on 2019-02-02 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190201_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
