# Generated by Django 2.1.2 on 2019-02-01 19:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20190201_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 2, 1, 19, 15, 55, 16303, tzinfo=utc))),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='buy',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='product',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
